import type { ComponentProps } from "react";
import MarketingPage from "./MarketingPage";

type Config = ComponentProps<typeof MarketingPage>["config"];

export const MARKETING_PAGES: Config[] = [
  {
    slug: "banners",
    title: "Create Stunning Banners | Lazy Faceless",
    headline: "Create Stunning Banners in Seconds",
    subheadline: "Design eye-catching banners for any platform — headers, covers, ads. No design skills needed.",
    description: "Professional banners for LinkedIn, Twitter, YouTube, and more. Pick a template, customize, download.",
    ctaText: "Create a Banner",
    features: [
      { icon: "🖼️", title: "Platform-Ready Sizes", description: "Pre-configured sizes for LinkedIn banners, Twitter headers, YouTube channel art, and Facebook covers." },
      { icon: "🎨", title: "Custom Backgrounds", description: "Upload your own images, use AI-generated backgrounds, or pick from curated color palettes." },
      { icon: "✨", title: "Pro Typography", description: "Choose from 24+ fonts including serif, sans-serif, cursive, and futuristic styles." },
    ],
    templateCategory: "bold",
  },
  {
    slug: "posts",
    title: "Create Social Media Posts | Lazy Faceless",
    headline: "Design Social Media Posts That Stand Out",
    subheadline: "Create beautiful, shareable posts for Instagram, LinkedIn, Twitter, and more.",
    description: "Stop using boring text posts. Create visual content that gets engagement.",
    ctaText: "Create a Post",
    features: [
      { icon: "📱", title: "Every Platform", description: "Square for Instagram, landscape for Twitter, portrait for Stories — all formats covered." },
      { icon: "💬", title: "Design Cards", description: "Turn your best thoughts, testimonials, and wisdom into stunning visual content." },
      { icon: "⚡", title: "30-Second Workflow", description: "Pick template → edit text → download. Your post is ready to publish." },
    ],
    templateCategory: "trendy",
  },
  {
    slug: "instagram",
    title: "Create Instagram Content | Lazy Faceless",
    headline: "Create Instagram Content That Gets Noticed",
    subheadline: "Design posts, stories, and reels covers that match your aesthetic and grow your audience.",
    description: "Beautiful Instagram content without Photoshop. Templates optimized for the Instagram algorithm.",
    ctaText: "Create for Instagram",
    features: [
      { icon: "📸", title: "Feed-Ready Posts", description: "1080×1080 square posts designed to look stunning in the Instagram grid." },
      { icon: "📖", title: "Story Templates", description: "9:16 story and reel cover designs that stop the scroll." },
      { icon: "🎯", title: "Consistent Aesthetic", description: "Keep your feed cohesive with matching fonts, colors, and styles across all posts." },
    ],
    templateCategory: "minimal",
  },
  {
    slug: "youtube",
    title: "Create YouTube Thumbnails & Banners | Lazy Faceless",
    headline: "YouTube Thumbnails & Banners That Get Clicks",
    subheadline: "Create attention-grabbing thumbnails and channel art that boost your views.",
    description: "Stand out in search results with professional thumbnails. No design experience required.",
    ctaText: "Create for YouTube",
    features: [
      { icon: "▶️", title: "Click-Worthy Thumbnails", description: "16:9 thumbnails designed to maximize your click-through rate." },
      { icon: "🖥️", title: "Channel Banners", description: "Professional channel art that looks great on desktop, tablet, and mobile." },
      { icon: "🔤", title: "Bold Typography", description: "Large, readable text that pops even at thumbnail size." },
    ],
    templateCategory: "bold",
  },
  {
    slug: "pinterest",
    title: "Create Pinterest Pins | Lazy Faceless",
    headline: "Create Pinterest Pins That Drive Traffic",
    subheadline: "Design tall, eye-catching pins optimized for the Pinterest feed and search.",
    description: "Pinterest-optimized pins in the perfect 2:3 ratio. Drive traffic to your site with beautiful designs.",
    ctaText: "Create a Pin",
    features: [
      { icon: "📌", title: "Optimized 2:3 Ratio", description: "Pins sized at 1000×1500 px — the ideal format for Pinterest's feed algorithm." },
      { icon: "🔍", title: "Search-Friendly", description: "Clean, readable designs that perform well in Pinterest visual search." },
      { icon: "🎀", title: "Aesthetic Templates", description: "Elegant and playful templates that match popular Pinterest aesthetics." },
    ],
    templateCategory: "elegant",
  },
  {
    slug: "facebook",
    title: "Create Facebook Content | Lazy Faceless",
    headline: "Create Facebook Posts & Covers That Engage",
    subheadline: "Design shareable posts, stories, and cover photos that grow your Facebook presence.",
    description: "Professional Facebook content in seconds. Optimized sizes for posts, stories, and cover photos.",
    ctaText: "Create for Facebook",
    features: [
      { icon: "👍", title: "Shareable Posts", description: "1200×630 posts designed for maximum engagement and sharing in the Facebook feed." },
      { icon: "📱", title: "Stories & Reels", description: "Full-screen 9:16 designs for Facebook Stories and Reels." },
      { icon: "🏠", title: "Cover Photos", description: "820×312 cover photos that make a great first impression on your page." },
    ],
    templateCategory: "playful",
  },
  {
    slug: "tiktok",
    title: "Create TikTok Content | Lazy Faceless",
    headline: "Create TikTok Content That Goes Viral",
    subheadline: "Design stunning cover images, design overlays, and text content for TikTok.",
    description: "Faceless TikTok content made easy. Create design videos, cover images, and text-based content.",
    ctaText: "Create for TikTok",
    features: [
      { icon: "🎵", title: "9:16 Vertical Format", description: "Full-screen vertical designs perfectly sized for TikTok's 1080×1920 format." },
      { icon: "🚀", title: "Faceless Content", description: "Create engaging content without showing your face — perfect for design and text accounts." },
      { icon: "🔥", title: "Trend-Ready", description: "Bold, eye-catching templates designed for the fast-scrolling TikTok feed." },
    ],
    templateCategory: "retro",
  },
  {
    slug: "linkedin",
    title: "Create LinkedIn Content | Lazy Faceless",
    headline: "Create LinkedIn Content That Builds Authority",
    subheadline: "Design professional posts, banners, and thought leadership content for LinkedIn.",
    description: "Stand out on LinkedIn with polished, professional visual content. Perfect for personal branding.",
    ctaText: "Create for LinkedIn",
    features: [
      { icon: "💼", title: "Professional Posts", description: "Clean, authoritative designs that match LinkedIn's professional tone." },
      { icon: "📊", title: "Thought Leadership", description: "Turn your expertise into shareable visual content that builds your brand." },
      { icon: "🏷️", title: "Banner & Profile", description: "LinkedIn banner images and profile-ready content that make connections." },
    ],
    templateCategory: "minimal",
  },
  {
    slug: "twitter",
    title: "Create X (Twitter) Content | Lazy Faceless",
    headline: "Create X Posts & Headers That Get Retweets",
    subheadline: "Design visual tweets, thread openers, and profile headers that grow your following.",
    description: "Make your tweets visual. Design cards and headers that stand out in the timeline.",
    ctaText: "Create for X",
    features: [
      { icon: "🐦", title: "Visual Tweets", description: "16:9 images that make your tweets stand out in the timeline." },
      { icon: "🧵", title: "Thread Openers", description: "Eye-catching first images that hook readers into your threads." },
      { icon: "🎯", title: "Profile Headers", description: "1500×500 headers that showcase your brand and message." },
    ],
    templateCategory: "bold",
  },
  {
    slug: "posters",
    title: "Create Posters & Flyers | Lazy Faceless",
    headline: "Create Posters & Flyers That Demand Attention",
    subheadline: "Design printable posters, event flyers, and wall art — bold typography, zero design skills.",
    description: "From motivational wall art to event announcements, create stunning posters in seconds.",
    ctaText: "Create a Poster",
    features: [
      { icon: "🖨️", title: "Print-Ready Sizes", description: "A4, A3, and US Letter formats optimized for crisp, high-quality printing." },
      { icon: "🎭", title: "Event & Promo Flyers", description: "Eye-catching designs for concerts, launches, sales, and community events." },
      { icon: "🖼️", title: "Wall Art & Designs", description: "Turn your favorite designs into frameable art with elegant layouts and typography." },
    ],
    templateCategory: "elegant",
  },
  {
    slug: "print",
    title: "Create Print-Ready Designs | Lazy Faceless",
    headline: "Create Print-Ready Designs in Seconds",
    subheadline: "Design business cards, flyers, menus, invitations, and more — formatted for professional printing.",
    description: "From business cards to event programs, create polished print materials without a designer.",
    ctaText: "Create for Print",
    features: [
      { icon: "🖨️", title: "Print-Perfect Formats", description: "A4, A5, US Letter, business card, and custom sizes with bleed-safe margins." },
      { icon: "📐", title: "High-Resolution Output", description: "Export at 300 DPI for crisp, professional results on any paper stock." },
      { icon: "🎨", title: "Brand-Ready Templates", description: "Menus, invitations, certificates, and more — customize colors, fonts, and layouts instantly." },
    ],
    templateCategory: "elegant",
  },
  {
    slug: "flyers",
    title: "Create Flyers | Lazy Faceless",
    headline: "Create Flyers That Get Results",
    subheadline: "Design professional flyers for events, promotions, and announcements — print-ready in seconds.",
    description: "Eye-catching flyers for any occasion. Choose a template, customize your message, and download in print-ready quality.",
    ctaText: "Create a Flyer",
    features: [
      { icon: "📄", title: "Print-Ready Sizes", description: "A4, A5, US Letter, and half-page formats ready for professional or home printing." },
      { icon: "🎉", title: "Event & Promo Designs", description: "Templates for sales, events, grand openings, classes, and community announcements." },
      { icon: "⚡", title: "Instant Customization", description: "Change text, colors, fonts, and backgrounds in seconds — no design skills needed." },
    ],
    templateCategory: "bold",
  },
  {
    slug: "business-cards",
    title: "Create Business Cards | Lazy Faceless",
    headline: "Create Business Cards That Leave an Impression",
    subheadline: "Design sleek, professional business cards with bold typography and custom layouts.",
    description: "Stand out at every meeting. Create print-ready business cards with your name, title, and contact info.",
    ctaText: "Create a Business Card",
    features: [
      { icon: "💼", title: "Standard Card Size", description: "3.5×2 inch format — the universal business card size, ready for any print shop." },
      { icon: "✨", title: "Premium Typography", description: "Choose from 24+ fonts to match your personal brand and professional style." },
      { icon: "🖨️", title: "High-Res Export", description: "Download at print-ready resolution for crisp text and sharp edges on any card stock." },
    ],
    templateCategory: "minimal",
  },
  {
    slug: "stickers",
    title: "Create Stickers | Lazy Faceless",
    headline: "Create Custom Stickers in Seconds",
    subheadline: "Design fun, bold stickers for laptops, water bottles, packaging, and merch — print or cut-ready.",
    description: "Turn designs, logos, and artwork into sticker-ready files. Download high-res files for printing at home or with any sticker service.",
    ctaText: "Create a Sticker",
    features: [
      { icon: "🏷️", title: "Sticker-Ready Sizes", description: "Square and circle formats sized perfectly for die-cut stickers, labels, and decals." },
      { icon: "🎨", title: "Bold & Fun Templates", description: "Eye-catching designs with vibrant colors, playful fonts, and standout typography." },
      { icon: "🖨️", title: "High-Res Download", description: "Export at print-ready resolution for crisp results on vinyl, paper, or holographic stock." },
    ],
    templateCategory: "playful",
  },
  {
    slug: "app-store",
    title: "Create App Store Screenshots | Lazy Faceless",
    headline: "Create App Store Screenshots That Convert",
    subheadline: "Design stunning screenshots for iOS App Store and Google Play that drive downloads.",
    description: "Professional app store assets in seconds. iPhone, iPad, Android, and Mac screenshot formats ready to upload.",
    ctaText: "Create App Screenshots",
    features: [
      { icon: "📱", title: "Every Device Size", description: "iPhone 6.7\", iPad 12.9\", Android phone, tablet, and Mac — all required sizes covered." },
      { icon: "🎯", title: "Conversion-Optimized", description: "Bold typography and clean layouts designed to maximize download rates." },
      { icon: "⚡", title: "Upload-Ready", description: "Pixel-perfect dimensions that meet Apple and Google's exact requirements." },
    ],
    templateCategory: "bold",
  },
  {
    slug: "google-play",
    title: "Create Google Play Screenshots | Lazy Faceless",
    headline: "Create Google Play Graphics That Get Downloads",
    subheadline: "Design feature graphics, screenshots, and promo images for your Android app.",
    description: "Stand out on Google Play with professional screenshots and feature graphics. All required formats included.",
    ctaText: "Create for Google Play",
    features: [
      { icon: "🤖", title: "Android Formats", description: "Phone (1080×1920) and tablet (1920×1200) screenshots sized to Google Play specs." },
      { icon: "🖼️", title: "Feature Graphics", description: "Eye-catching 1024×500 feature graphics that showcase your app's best features." },
      { icon: "🎨", title: "Consistent Branding", description: "Keep your app's visual identity consistent across all store listing assets." },
    ],
    templateCategory: "trendy",
  },
  {
    slug: "phone-backgrounds",
    title: "Create Phone Backgrounds | Lazy Faceless",
    headline: "Create Phone Wallpapers That Inspire",
    subheadline: "Design beautiful lock screen and home screen backgrounds with designs, colors, and custom typography.",
    description: "Turn your phone into a daily dose of motivation. Create stunning wallpapers for iPhone and Android in the exact sizes your device needs.",
    ctaText: "Create a Wallpaper",
    features: [
      { icon: "📱", title: "Every Phone Size", description: "iPhone, Android, and lock screen formats — pixel-perfect for any device." },
      { icon: "🎨", title: "Custom Aesthetics", description: "Choose fonts, colors, and backgrounds that match your personal style." },
      { icon: "💬", title: "Design Wallpapers", description: "Turn your favorite designs into daily reminders on your home or lock screen." },
    ],
    templateCategory: "elegant",
  },
];
